---

- name: packages undependencies
  apt: >
    pkg={{ item }}
    state=absent
  with_items:
    - supervisor
  sudo: yes

- name: config unfile
  file: >
      path=/etc/default/supervisor
      state=absent
  sudo: yes

- name: packages dependencies
  apt: >
    pkg={{ item }}
    state=present
  with_items:
    - python-pip
  sudo: yes

- name: packages
  pip: >
    name={{ item }}
    state=present
  with_items:
    - supervisor
  sudo: yes

- name: log directory
  file: >
      path=/var/log/supervisor
      state=directory
      group=root
      owner=root
      mode=0755
  sudo: yes

- name: config template
  template: >
    src=config.j2
    dest=/etc/supervisor/supervisord.conf
  sudo: yes

- name: config file
  file: >
      path=/etc/supervisor/supervisord.conf
      state=file
      group=root
      owner=root
      mode=0755
  sudo: yes

- name: config directory
  file: >
      path=/etc/supervisor/conf.d
      state=directory
      group=root
      owner=root
      mode=0755
  sudo: yes

- name: service template
  template: >
    src=service.j2
    dest=/etc/init.d/supervisor
  sudo: yes

- name: service file
  file: >
      path=/etc/init.d/supervisor
      state=file
      group=root
      owner=root
      mode=0755
  sudo: yes

- name: service install
  shell: >
      /usr/sbin/update-rc.d supervisor defaults
      creates=/etc/rc0.d/K01supervisor
  sudo: yes

- name: service
  service: >
      name=supervisor
      state=started
      enabled=true
  sudo: yes
