---

- name: packages
  apt: >
    name={{ item }}
    state=present
  with_items:
    - supervisor
  sudo: yes

- name: service
  service: >
    name=supervisor
    state=started
    enabled=true
  sudo: yes

- name: config template httpd
  template: >
    src=inet_http_server.conf.j2
    dest=/etc/supervisor/conf.d/inet_http_server.conf
  notify:
    - supervisor restart
  when: elao_supervisor_httpd|bool
  sudo: yes

- name: config template not httpd
  file: >
    path=/etc/supervisor/conf.d/inet_http_server.conf
    state=absent
  notify:
    - supervisor restart
  when: not elao_supervisor_httpd|bool
  sudo: yes
