---

- name: supervisor restart
  service: >
    name=supervisor
    state=restarted
  register: command_result
  failed_when: 'command_result|failed and ''Stopping supervisor: supervisord.'' not in command_result.msg'
  sudo: yes
